# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Back of the Frontend
email: shanehealy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  All things Angular 1.x and maybe even 2.0
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.shanehealy.io" # the base hostname & protocol for your site
twitter_username: MrShaneHealy
github_username:  MrShaneH

# Build settings
markdown: kramdown
